packages:
  - packages/*
  - apps/*
  - tools/*
  - '!**/node_modules'
  - '!**/dist'
  - '!**/build'
  - '!**/.next'
  - '!**/coverage'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@sentry/cli'
  - core-js
  - esbuild
  - lefthook
  - sharp
